-- BrainBites large seed data
-- Target: 1000 users, 5000 posts, 20000 likes
-- Compatible with MySQL 5.7+/8+ and MariaDB
-- Run this after importing schema (and categories table exists)

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Keep categories, reset content tables
DELETE FROM `likes`;
DELETE FROM `posts`;
DELETE FROM `users`;
ALTER TABLE `likes` AUTO_INCREMENT = 1;
ALTER TABLE `posts` AUTO_INCREMENT = 1;
ALTER TABLE `users` AUTO_INCREMENT = 1;

-- Ensure baseline categories exist
INSERT IGNORE INTO `categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES
  (1, 'Technology', 'technology', 'AI, apps, tools, and coding questions.', NOW(), NOW()),
  (2, 'Science', 'science', 'Physics, biology, and space explained simply.', NOW(), NOW()),
  (3, 'Health', 'health', 'Fitness, nutrition, and mental wellness.', NOW(), NOW()),
  (4, 'Finance', 'finance', 'Saving, budgeting, investing, and money basics.', NOW(), NOW()),
  (5, 'Education', 'education', 'Learning methods and study strategies.', NOW(), NOW());

-- 1000 users
INSERT INTO `users` (`name`, `email`, `role`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`)
SELECT
  CASE WHEN nums.n = 1 THEN 'Admin User' ELSE CONCAT('User ', nums.n) END AS name,
  CASE WHEN nums.n = 1 THEN 'admin@brainbites.local' ELSE CONCAT('user', nums.n, '@brainbites.local') END AS email,
  CASE WHEN nums.n = 1 THEN 'admin' ELSE 'reader' END AS role,
  NOW() AS email_verified_at,
  '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' AS password,
  NULL AS remember_token,
  NOW() AS created_at,
  NOW() AS updated_at
FROM (
  SELECT (ones.i + tens.i * 10 + hundreds.i * 100) + 1 AS n
  FROM
    (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
    CROSS JOIN (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds
) AS nums
WHERE nums.n <= 1000;

-- 5000 posts
INSERT INTO `posts` (`user_id`, `category_id`, `title`, `slug`, `summary`, `body`, `image_path`, `image_mime`, `image_base64`, `is_public`, `published_at`, `created_at`, `updated_at`)
SELECT
  ((nums.n - 1) % 1000) + 1 AS user_id,
  ((nums.n - 1) % 5) + 1 AS category_id,
  CONCAT('Generated Post ', nums.n) AS title,
  CONCAT('generated-post-', nums.n) AS slug,
  CONCAT('Auto-generated summary for post ', nums.n, '.') AS summary,
  CONCAT('This is autogenerated body content for post #', nums.n, '. It exists for load testing and UI validation.') AS body,
  'embedded' AS image_path,
  'image/svg+xml' AS image_mime,
  TO_BASE64(CONCAT(
    '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630">',
    '<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">',
    '<stop offset="0%" stop-color="hsl(', MOD(nums.n * 37, 360), ',72%,42%)"/>',
    '<stop offset="100%" stop-color="#0f172a"/>',
    '</linearGradient></defs>',
    '<rect width="100%" height="100%" fill="url(#g)"/>',
    '<text x="64" y="250" fill="white" font-size="68" font-family="Arial, sans-serif" font-weight="700">Generated Post ', nums.n, '</text>',
    '<text x="64" y="330" fill="#bae6fd" font-size="34" font-family="Arial, sans-serif">Category ', ((nums.n - 1) % 5) + 1, ' • BrainBites Seed</text>',
    '</svg>'
  )) AS image_base64,
  1 AS is_public,
  DATE_SUB(NOW(), INTERVAL (nums.n % 365) DAY) AS published_at,
  NOW() AS created_at,
  NOW() AS updated_at
FROM (
  SELECT (ones.i + tens.i * 10 + hundreds.i * 100 + thousands.i * 1000) + 1 AS n
  FROM
    (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
    CROSS JOIN (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds
    CROSS JOIN (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) thousands
) AS nums
WHERE nums.n <= 5000;

-- 20000 unique likes
-- Mapping guarantees uniqueness under unique(user_id, post_id):
-- user_id in [1..4], post_id in [1..5000], total = 4 * 5000 = 20000
INSERT INTO `likes` (`user_id`, `post_id`, `created_at`, `updated_at`)
SELECT
  FLOOR((nums.n - 1) / 5000) + 1 AS user_id,
  ((nums.n - 1) % 5000) + 1 AS post_id,
  NOW() AS created_at,
  NOW() AS updated_at
FROM (
  SELECT (ones.i + tens.i * 10 + hundreds.i * 100 + thousands.i * 1000 + tenthousands.i * 10000) + 1 AS n
  FROM
    (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
    CROSS JOIN (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds
    CROSS JOIN (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) thousands
    CROSS JOIN (SELECT 0 AS i UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tenthousands
) AS nums
WHERE nums.n <= 20000;

SET FOREIGN_KEY_CHECKS = 1;

-- Optional verification
SELECT 'users' AS table_name, COUNT(*) AS row_count FROM `users`
UNION ALL
SELECT 'posts', COUNT(*) FROM `posts`
UNION ALL
SELECT 'likes', COUNT(*) FROM `likes`;
